app1/urls.py
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from django.urls import path, include

from . import views
from .views import CadastroListView, CadastroUpdateView, CadastroDeleteView, IndexCadastroTemplateView

router = routers.DefaultRouter()
router.register(r"events", views.EventViewSet)
router.register(r"comments", views.CommentViewSet)

app_name = 'app1'

urlpatterns = [
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),
    path('noticia', views.noticia, name='noticia'),
    path('manutencao', views.manutencao, name='manutencao'),
    path('api-token-auth/', obtain_auth_token, name="api_token_auth"),
    path('cadastro/', views.cadastro, name="cadastrar"),
    path('cadastrado', CadastroListView.as_view(), name="lista_cadastro"),
    path('cadastro/<pk>', CadastroUpdateView.as_view(), name="atualiza_cadastro"),
    path('cadastro/excluir/<pk>', CadastroDeleteView.as_view(), name="deleta_cadastro"),
    path('principalcadastro/', IndexCadastroTemplateView.as_view(), name="principal_cadastro"),
    path("api/v1/", include(router.urls)),
    path("agenda", views.agenda, name="agenda-events"),
    path("all", views.all, name="agenda-events-all"),
    path("<int:id>", views.show, name="agenda-events-show"),
    path("<int:year>/<int:month>/<int:day>", views.day, name="agenda-events-day"),
    path("new", views.new, name="agenda-events-new"),
    path("delete/<int:id>", views.delete, name="agenda-events-delete"),
    path("edit", views.edit, name="agenda-events-edit"),

]

covid/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path
from app1 import views


urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

app1/forms.py
from django import forms
from django.contrib.auth.models import User
from django_cpf_cnpj.fields import CPFField

from app1.models import Cadastro, Comment, Event


# Fomulario Cadastro
class FormCadastro(forms.Form):
    SEXO_CHOICES = [
        ["Feminino", "Feminino"],
        ["Masculino", "Masculino"]
    ]
    GRUPO_CHOICES = [
        ["Selecione uma Opção", "Selecione uma Opção"],
        ["Profissional de saúde", "Profissional de saúde"],
        ["Trabalhador em saúde sem conselho de classe", "Trabalhador em saúde sem conselho de classe"],
        ["Doula", "Doula"],
        ["Cuidador", "Cuidador"],
        ["Acamado com 60 anos ou mais", "Acamado com 60 anos ou mais"],
        ["Pessoa com 80 anos ou mais", "Pessoa com 80 anos ou mais"],
        ["Pessoa entre 75 e 79 anos", "Pessoa entre 75 e 79 anos"],
        ["Pessoa entre 70 e 74 anos", "Pessoa entre 70 e 74 anos"],
        ["Pessoa entre 65 e 69 anos", "Pessoa entre 65 e 69 anos"],
        ["Pessoa entre 60 e 64 anos", "Pessoa entre 60 e 64 anos"],
        ["População Geral de 45 a 59 anos", "População Geral de 45 a 59 anos"],
        ["Policial Militar", "Policial Militar"],
        ["Policial Civil", "Policial Civil"],
        ["Policial Federal", "Policial Federal"],
        ["Agente da Receita Federal", "Agente da Receita Federal"],
        ["Policial Rodoviário", "Policial Rodoviário"],
        ["Agente Penitenciário / Policial Penal", "Agente Penitenciário / Policial Penal"],
        ["Trabalhadores de Unidades Socioeducativas", "Trabalhadores de Unidades Socioeducativas"],
        ["Trabalhador do Sistema Prisional", "Trabalhador do Sistema Prisional"],
        ["Bombeiro Civil", "Bombeiro Civil"],
        ["Bombeiro Militar", "Bombeiro Militar"],
        ["Guarda Municipal", "Guarda Municipal"],
        ["Membro do Exército", "Membro do Exército"],
        ["Membro da Marinha", "Membro da Marinha"],
        ["Membro da Aeronáutica", "Membro da Aeronáutica"],
        ["Trabalhador de Transporte Aéreo", "Trabalhador de Transporte Aéreo"],
        ["Professor", "Professor"],
        ["Trabalhador da Educação", "Trabalhador da Educação"],
        ["Assistente Social", "Assistente Social"],
        ["Trabalhador da Assistência Social", "Trabalhador da Assistência Social"],
        ["População Privada de Liberdade", "População Privada de Liberdade"],
    ]
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    CPF = forms.CharField()
    first_name = forms.CharField(label='Nome Completo')
    email = forms.EmailField()
    telefone = forms.CharField()
    endereco = forms.CharField()
    numero = forms.CharField()
    complemento = forms.CharField()
    bairro = forms.CharField()
    CEP = forms.CharField()
    nascimento = forms.DateField(label='Data de Nascimento', localize=True, required=True,
                                 widget=forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'}))
    sexo = forms.ChoiceField(choices=SEXO_CHOICES)
    grupo = forms.ChoiceField(choices=GRUPO_CHOICES)

    class Meta:
        model = Cadastro
        fields = '__all__'

    def __str__(self):
        return self.first_name

# Formulario Agenda de Serviços
class EventForm(forms.ModelForm):
    """Formulário utilizado para a inserção de novos eventos."""

    class Meta:
        model = Event
        fields = ["date", "event", "priority"]

    def __str__(self):
        return self.event


class CommentForm(forms.ModelForm):
    """Formulário usado para a inserção de comentários em um serviço."""

    class Meta:
        model = Comment
        fields = ["text", "author", "email", "event"]

app1/views.py
from datetime import datetime, timedelta

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, InvalidPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.timezone import localdate
from django.views.defaults import bad_request, server_error
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView
from rest_framework import filters, viewsets
from rest_framework.permissions import IsAuthenticated


from app1.forms import EventForm, CommentForm, FormCadastro
from app1.models import Event, Comment, Cadastro
from .serializers import CommentSerializer, EventSerializer
from .services import split_str_date

ITEMS_PER_PAGE = 5
FIRST_PAGE = 1


# PÁGINA PRINCIPAL INDEX
# ----------------------------------------------
def indexx(request):
    return render(request, 'app3/index.html')

# ----------------------------------------------
def noticia(request):
    return render(request, 'app3/noticia.html')

def manutencao(request):
    return render(request, 'app3/manutencao.html')

def cadastro(request):
    if request.method == 'POST':
        form = FormCadastro(request.POST)
        if form.is_valid():
            usuario = User()
            usuario.first_name = form.cleaned_data['first_name']
            usuario.email = form.cleaned_data['email']
            usuario.username = form.cleaned_data['username']
            usuario.password = form.cleaned_data['password']

            usuario.save()
            usuario.set_password(usuario.password)
            usuario.save()

            cad = Cadastro()
            cad.CPF = form.cleaned_data['CPF']
            cad.nascimento = form.cleaned_data['nascimento']
            cad.telefone = form.cleaned_data['telefone']
            cad.endereco = form.cleaned_data['endereco']
            cad.complemento = form.cleaned_data['complemento']
            cad.numero = form.cleaned_data['numero']
            cad.bairro = form.cleaned_data['bairro']
            cad.CEP = form.cleaned_data['CEP']
            cad.grupo = form.cleaned_data['grupo']
            cad.sexo = form.cleaned_data['sexo']

            cad.usuario = usuario
            cad.save()
            return HttpResponseRedirect(reverse('app1:lista_cadastro'))
    else:
        form = FormCadastro()

    return render(request, 'app3/cadastrar.html', {'form': form})

# PÁGINA PRINCIPAL FUNCIONARIO
# ----------------------------------------------

class IndexCadastroTemplateView(TemplateView):
    template_name = "app3/principal.html"

# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroListView(ListView):
    template_name = "app3/lista.html"
    model = Cadastro
    context_object_name = "cadastrado"


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroUpdateView(UpdateView):
    template_name = "app3/confirmar.html"
    model = Cadastro
    fields = '__all__'
    context_object_name = 'cadastro'
    success_url = reverse_lazy("app1:lista_cadastro")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroDeleteView(DeleteView):
    template_name = "app3/index.html"
    model = Cadastro
    context_object_name = 'cadastro'
    success_url = reverse_lazy("app1:lista_cadastro")

# PÁGINA PRINCIPAL LOGIN
# ----------------------------------------------
def loginn(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')
        senha = request.POST.get('senha')
        user = authenticate(username=usuario, password=senha)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app1:indexx'))
            else:
                return HttpResponse("Sua Conta Não Esta Ativa.")
        else:
            print("Alguém Tentou Fazer Login e Falhou")
            print("Foi Usado userName: {} e senha: {}".format(usuario, senha))
            return HttpResponse("O Login ou Senha Está Incorreto.")

    else:
        return render(request, 'app3/login.html', {})

# PÁGINA PRINCIPAL LOGOUT
# ----------------------------------------------
@login_required
def logoutt(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

class EventViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Event.objects.all()
    serializer_class = EventSerializer

    permission_classes = (IsAuthenticated,)


class CommentViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ("event__id",)

    permission_classes = (IsAuthenticated,)

# PÁGINA PRINCIPAL AGENDA
# ----------------------------------------------
@login_required
def agenda(request):
    """
    Exibe a página principal da aplicaão.
    """
    context = {
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/agenda.html", context)


@login_required
def all(request):
    """
    Exibe todas os eventos consolidados em uma única página, recebe o
    número da página a ser visualizada via GET.
    """

    page = request.GET.get("page", FIRST_PAGE)
    paginator = Paginator(Event.objects.all(), ITEMS_PER_PAGE)
    total = paginator.count

    try:
        events = paginator.page(page)
    except InvalidPage:
        events = paginator.page(FIRST_PAGE)

    context = {
        "events": events,
        "total": total,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/events.html", context)


@login_required
def day(request, year: int, month: int, day: int):
    """
    Visualização dos eventos de um determinado dia, recebe a data em
    formato ano/mês/dia como parâmtro.
    """


    day = datetime(year, month, day)
    filted_events = Event.objects.filter(
        date="{:%Y-%m-%d}".format(day)
    ).order_by("-priority", "event")

    context = {
        "today": localdate(),
        "day": day,
        "events": filted_events,
        "next": day + timedelta(days=1),
        "previous": day - timedelta(days=1),
        "priorities": Event.priorities_list,
    }

    return render(request, "app3/agenda/day.html", context)


@login_required
def delete(request, id: int):
    """
    Apaga um evento específico, se o evento não existir resultará em
    erro 404, se algo errado ocorrer retornará a página de erro.
    """
    event = get_object_or_404(Event, id=id)
    (year, month, day) = split_str_date("{:%Y-%m-%d}".format(event.date))

    if event.delete():
        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return server_error(request, "ops_500.html")


@login_required
def edit(request):
    """
    Edita o conteúdo de um evento, recebendo os dados enviados pelo
    formulário, validando e populando em um evento já existente.
    """
    form = EventForm(request.POST)

    if form.is_valid():
        event = get_object_or_404(Event, id=request.POST["id"])
        event.date = form.cleaned_data["date"]
        event.event = form.cleaned_data["event"]
        event.priority = form.cleaned_data["priority"]
        event.save()
        (year, month, day) = split_str_date("{:%Y-%m-%d}".format(event.date))
        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return bad_request(request, None, "ops_400.html")


@login_required
def new(request):
    """
    Recebe os dados de um novo evento via POST, faz a validação dos dados
    e aí insere na base de dados.
    """
    form = EventForm(request.POST)

    if form.is_valid():
        form.save(commit=True)
        # e uso a data enviada pelo formulário para o redirecionamento.
        year, month, day = split_str_date(request.POST["date"])

        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return bad_request(request, None, "ops_400.html")


def show(request, id: int):
    """
    Visualização de um determinado evento e de seus comentários, recebe
    o 'id' do evento. Caso seja acessado via POST insere um novo comentário.
    """
    event = get_object_or_404(Event, id=id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("app1:agenda-events-show", id=id)

    context = {
        "event": event,
        "comments": Comment.objects.filter(event=id).order_by("-commented"),
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/show.html", context)

app1/templates/app3/_layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="shortcut icon" href="{% static 'app2/imgs/logo.png' %}" type="image/png">

		<script src="https://kit.fontawesome.com/d64caa891a.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'app2/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'app2/css/style_default.css' %}">

		<link rel="stylesheet" href="{% static 'app2/css/style.css' %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
		<script src="{% static 'app2/js/jquery.min.js' %}"></script>
		<script src="{% static 'app2/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'app2/js/events.js' %}"></script>
        <script src="{% static 'app2/js/formgeral.js' %}"></script>

	    <meta name="keywords" content="Vacinaçao Covid-19">
	    <meta name="description" content="Vacinaçao Covid-19">
	    <meta name="author" content="Vacinaçao Covid-19">

	    <!--<script type="text/javascript">!function(t,e){t.artibotApi={l:[],t:[],on:function(){this.l.push(arguments)},
	    trigger:function(){this.t.push(arguments)}};var a=!1,i=e.createElement("script");i.async=!0,i.
	    type="text/javascript",i.src="https://app.artibot.ai/loader.js",e.getElementsByTagName("head").item(0).
	    appendChild(i),i.onreadystatechange=i.onload=function(){if(!(a||this.readyState&&"loaded"!=this.
	    readyState&&"complete"!=this.readyState)){new window.ArtiBot({i:"ccb476d7-4734-4440-9a1f-f2b7caef8a83"});
	    a=!0}}}(window,document);</script>-->

	    <script>

					</script>
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="{% static 'app2/js/js.js' %}"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', 'UA-147102043-1');
		</script>

	</head>

	<body class="">
		<div id="fb-root"></div>
		<script async defer crossorigin="anonymous" src="{% static 'app2/js/sdk.js' %}"></script>

		<!--## LOADER ##-->
		<div class="page-loader-wrapper">
		   	<div class="loader">
		      	<div class="preloader"><div class="spinner-layer">
		            <div class="circle-clipper left"><div class="circle"></div></div>
		            <div class="circle-clipper right"><div class="circle"></div></div>
	         	</div></div>
		      	<p style="font-size: 16px;">CARREGANDO...</p>
		   	</div>
		</div>

		<div id="content">
			<!--## TOPO ##-->
			<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 pad_lr10 topo">
				<div class="col-md-8 col-lg-8 col-sm-8 col-xs-12 pad_m0">
					<nav>
						<p class="upper fl_left"></p>
		          		<li class="dropdown menu_acessibilidade nav navbar-nav" >
		          			<a title="Acessibilidade" class="nav-link" href="#" style="text-decoration: none">
                                <strong>Acessibilidade</strong><img src="{% static 'app2/imgs/bilidade.png' %}" class="img-fluid" alt=""/>
                                </a>
							<ul class="dropdown-menu nav">
								<li><a class="nav-link active" href="#" style="text-decoration: none" id="btnAumentar">
                                    <i class="fa fa-search-plus"></i> Aumentar fonte</a></li>
								<li><a class="nav-link active" href="#" style="text-decoration: none" id="btnDiminuir">
                                    <i class="fa fa-search-minus"></i> Diminuir fonte</a></li>
								<li><a class="nav-link active" href="#" style="text-decoration: none" onClick="window.toggleContrast()">
                                    <i class="fa fa-adjust"></i> Alto contraste</a></li>
								<li><a class="nav-link active" href="#" style="text-decoration: none" id="btnSublinhar">
                                    <i class="fa fa-underline"></i> Sublinhar Links</a></li>
								<li><a class="nav-link active" href="#" style="text-decoration: none" id="btnGrayscale">
                                    <i class="fa fa-gears"></i> Escalas de Cinza</a></li>
								<li><a class="nav-link active" href="#" style="text-decoration: none" id="btnReset">
                                    <i class="fa fa-refresh ml-5"></i> Resetar</a></li>
							</ul>
		          		</li>

					</nav>
				</div>

				<div class="col-md-4 col-lg-4 col-sm-4 col-xs-12 desktop">
					<p class="fl_right social_icons">
						<a href="https://www.facebook.com/minsaude/" target="_blank" title="Facebook">
                            <img src="{% static 'app2/imgs/facebook.png' %}" alt="Logo do Facebook"></a>
						<a href="https://www.instagram.com/minsaude/" target="_blank" title="Instagram">
                            <img src="{% static 'app2/imgs/insta.png' %}" alt="Logo do Instagram"></a>
					</p>

				</div>
			</div>
			<div class="clear"></div>

			<!--## MENU TOPO ##-->
			<div id="menu_fixo" class="">
		      	<nav class="navbar navbar-dark bg-primary">
		         	<div class="navbar-header menu_mobile">
			            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#menu" aria-expanded="false">
			               <span class="sr-only">Toggle navigation</span>
			               <span class="icon-bar"></span>
			               <span class="icon-bar"></span>
			               <span class="icon-bar"></span>
			            </button>

			            <a class="navbar-brand visible-xs" href="{% url 'app1:indexx' %}">
                            <img class="logo_menu mobile" alt="Logo Vacinação Covid-19"
                                 src="{% static 'app2/imgs/logo3.png' %}"></a>
			        </div>

		         	<div class="collapse navbar-collapse default_home menu_mobile" id="menu">
		          		<div class="col-md-12 pad_lr10">

						    <div class="navbar-header col-4 col-md-2 offset-md-3">
					 	      	<a href="{% url 'app1:indexx' %}"><img class="logo_menu desktop"
                                    alt="Vacinaçao Covid-19" src="{% static 'app2/imgs/logo3.png' %}"></a>
						    </div>

			            	<ul class="nav navbar-nav navbar-right menu_principal">
			            		<a class="btn_fechar azul_claro fl_right mobile" data-toggle="collapse" data-target="#menu" aria-expanded="true">
									<img src="{% static "app2/imgs/fechar.png" %}" class="icon_30 mar_r3" alt="Fechar">
			            		</a>

			     	            	<li class="dropdown">
						              		<li>
						                		<a href="{% url 'app1:login' %}" style="font-size: 17px"><strong>Login</strong></a>
						              		</li>

									    					<li>
						                		<a href="{% url 'app1:manutencao' %}" style="font-size: 15px"><strong>Agente</strong></a>
						              		</li>
									    	<li>
						                		<a href="{% url 'app1:noticia' %}" style="font-size: 15px"><strong>Notícias</strong></a>
						              		</li>
								    	    <li>
						                		<a href="{% url 'app1:principal_cadastro' %}" style="font-size: 15px"><strong>Cadastrar</strong></a>
						              		</li>
                                            <li>
						                		<a href="{% url 'app1:agenda-events' %}" style="font-size: 15px"><strong>Agenda</strong></a>
						              		</li>
                                            <li class="nav-item">
                                                 <a class="nav-item text-dark nav-link" href="{% url 'admin:index' %}">Admin</a>
                                            </li>



			              		<li id="li_contato"></li>


								<div class="clear"></div>
		            		</ul>
		          		</div>
		        	</div>
		      	</nav>
			</div>
			<div class="clear"></div>


<title>Covid-19 | Vacinação</title>

<link rel="stylesheet" type="text/css" href="{% static 'app2/css/slick.css' %}">
<script type='text/javascript' src="{% static 'app2/js/slick.min.js' %}"></script>



<!-- Conteúdo do site -->
                     {% block conteudo %}

                     {% endblock %}





<div class="clear pad_t5"></div>

<style>
	.page_content img { max-width: 100% !important; height: auto !important; }
	.pre-title { padding: 8px 12px !important; }
</style>

			<!--## Rodapé ##-->
			<!--<a href="#"><img id="img_topo" src=""/></a>-->


			<div style="margin-top: 1px; "></div>
<style>
.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: #2C354A;
  color: white;
  text-align: center;
}
</style>
			<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 pad_lr10 pad_t1 pad_b1 footer rodape">
					<p class="azul_claro font-weight-normal text_center mar_0"
                       style="font-family: 'Ubuntu'">Desenvolvido por Isabella Fraga, Michell Leonne e Rogério Dagnon ®</p>
				</div>
			</div>

		</div>

		<script src="{% static 'app2/js/scripts.js' %}"></script>
		<script src="h{% static 'app2/js/jquery-scrolltofixed.js' %}"></script>

		<script>
			$(document).ready(function() {
				setTimeout(function () { $('.page-loader-wrapper').fadeOut(); }, 30);

    			$('.dropdown').click(function () {
      				var target = $(this).find('img');

    				if ($(this).hasClass('open')) {
    					$(this).removeClass('open');
      					target.attr('src', '{% static "app2/imgs/ArrowRight_menu.png" %}');
    				} else {
    					$(this).addClass('open');
      					target.attr('src', '{% static "app2/imgs/ArrowRight_menu.png" %}');
    				}
  				});
 			});
		</script>

		<div vw class="enabled">
			<div vw-access-button class="active"></div>
				<div vw-plugin-wrapper>
				<div class="vw-plugin-top-wrapper"></div>
			</div>
		</div>

		<script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
		<script>
			new window.VLibras.Widget('https://vlibras.gov.br/app');
		</script>


    </script>


		<style>
			div[vw] { top: 50% !important; }
		</style>
	</body>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <!-- Importando o js do bootstrap -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app1/templates/app3/_layouts/index.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}{% load static %}
{% load widget_tweaks %}
{% block conteudo %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8"/>
        <title></title>
        <link rel="stylesheet" type="text/css" href="style.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    </head>
    <body>
        <div id="formulario">
            <form name="cadastro" method="post">
                <div class="form-group col-md-12">
                      <label for="inputNome">Nome Completo</label>
                       {% render_field form.first_name class+="form-control" %}
                </div>
                <div class="campo">
                    <label id="tel">Telefone fixo/móvel</label>
                    <input type="text" class="telefone" pattern=".{13,14}" maxlength="14" name="Telefone" placeholder="(xx)xxxxx-xxxx" required>
                    <label id="respostaTel" class="animated shake"></label>
                </div>
                <div class="campo">
                    <label id="CPF">CPF</label>
                    <input type="text" class="CPF" maxlength="11" name="CPF" placeholder="xxx.xxx.xxx-xx" required>
                    <label id="respostaCPF" class="animated shake">O CPF digitado não existe</label>
                </div>
                <div class="campo">
                    <label>CEP</label>
                    <input name="CEP" type="text" id="CEP" maxlength="9" placeholder="xxxxx-xxx" required/>
                    <label id="respostaCep" class="animated shake"></label>
                </div>
                <div class="campo">
                    <label>Rua</label>
                    <input name="rua" type="text" id="rua" required/>
                </div>
                <div class="campo">
                    <label>Bairro</label>
                    <input name="bairro" type="text" id="bairro" required/>
                </div>
                <div class="campo">
                    <label>Cidade</label>
                    <input name="cidade" type="text" id="cidade" required/>
                </div>
                <div class="campo">  
                    <label>Estado</label>
                    <input name="uf" type="text" id="uf" required/>
                </div>

                <input type="submit" value="Cadastrar">
            </form>
        </div>
        <script src="form-validacoes.js"></script>
    </body>
</html>
{% endblock %}

app1/templates/app3/_layouts/pagination.html
<!-- Paginação Lista Agenda -->
{% if paginated.has_other_pages %}
    <ul class="pagination justify-content-center">
    {% if paginated.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ paginated.previous_page_number }}">&laquo;</a>
        </li>
    {% else %}
        <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
    {% endif %}
    {% for page in paginated.paginator.page_range %}
        {% if paginated.number == page %}
        <li class="page-item active"><a class="page-link">{{ page }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
    {% endif %}
    {% endfor %}
    {% if paginated.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ paginated.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
    {% endif %}
  </ul>
{% endif %}