app1/urls.py
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from django.urls import path, include

from . import views
from .views import CadastroListView, CadastroUpdateView, CadastroDeleteView, IndexCadastroTemplateView

router = routers.DefaultRouter()
router.register(r"events", views.EventViewSet)
router.register(r"comments", views.CommentViewSet)

app_name = 'app1'

urlpatterns = [
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),
    path('noticia', views.noticia, name='noticia'),
    path('manutencao', views.manutencao, name='manutencao'),
    path('api-token-auth/', obtain_auth_token, name="api_token_auth"),
    path('cadastro/', views.cadastro, name="cadastrar"),
    path('cadastrado', CadastroListView.as_view(), name="lista_cadastro"),
    path('cadastro/<pk>', CadastroUpdateView.as_view(), name="atualiza_cadastro"),
    path('cadastro/excluir/<pk>', CadastroDeleteView.as_view(), name="deleta_cadastro"),
    path('principalcadastro/', IndexCadastroTemplateView.as_view(), name="principal_cadastro"),
    path("api/v1/", include(router.urls)),
    path("agenda", views.agenda, name="agenda-events"),
    path("all", views.all, name="agenda-events-all"),
    path("<int:id>", views.show, name="agenda-events-show"),
    path("<int:year>/<int:month>/<int:day>", views.day, name="agenda-events-day"),
    path("new", views.new, name="agenda-events-new"),
    path("delete/<int:id>", views.delete, name="agenda-events-delete"),
    path("edit", views.edit, name="agenda-events-edit"),

]

covid/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path
from app1 import views


urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

app1/forms.py
from django import forms
from django.contrib.auth.models import User
from django_cpf_cnpj.fields import CPFField

from app1.models import Cadastro, Comment, Event


# Fomulario Cadastro
class FormCadastro(forms.Form):
    SEXO_CHOICES = [
        ["Feminino", "Feminino"],
        ["Masculino", "Masculino"]
    ]
    GRUPO_CHOICES = [
        ["Selecione uma Opção", "Selecione uma Opção"],
        ["Profissional de saúde", "Profissional de saúde"],
        ["Trabalhador em saúde sem conselho de classe", "Trabalhador em saúde sem conselho de classe"],
        ["Doula", "Doula"],
        ["Cuidador", "Cuidador"],
        ["Acamado com 60 anos ou mais", "Acamado com 60 anos ou mais"],
        ["Pessoa com 80 anos ou mais", "Pessoa com 80 anos ou mais"],
        ["Pessoa entre 75 e 79 anos", "Pessoa entre 75 e 79 anos"],
        ["Pessoa entre 70 e 74 anos", "Pessoa entre 70 e 74 anos"],
        ["Pessoa entre 65 e 69 anos", "Pessoa entre 65 e 69 anos"],
        ["Pessoa entre 60 e 64 anos", "Pessoa entre 60 e 64 anos"],
        ["População Geral de 45 a 59 anos", "População Geral de 45 a 59 anos"],
        ["Policial Militar", "Policial Militar"],
        ["Policial Civil", "Policial Civil"],
        ["Policial Federal", "Policial Federal"],
        ["Agente da Receita Federal", "Agente da Receita Federal"],
        ["Policial Rodoviário", "Policial Rodoviário"],
        ["Agente Penitenciário / Policial Penal", "Agente Penitenciário / Policial Penal"],
        ["Trabalhadores de Unidades Socioeducativas", "Trabalhadores de Unidades Socioeducativas"],
        ["Trabalhador do Sistema Prisional", "Trabalhador do Sistema Prisional"],
        ["Bombeiro Civil", "Bombeiro Civil"],
        ["Bombeiro Militar", "Bombeiro Militar"],
        ["Guarda Municipal", "Guarda Municipal"],
        ["Membro do Exército", "Membro do Exército"],
        ["Membro da Marinha", "Membro da Marinha"],
        ["Membro da Aeronáutica", "Membro da Aeronáutica"],
        ["Trabalhador de Transporte Aéreo", "Trabalhador de Transporte Aéreo"],
        ["Professor", "Professor"],
        ["Trabalhador da Educação", "Trabalhador da Educação"],
        ["Assistente Social", "Assistente Social"],
        ["Trabalhador da Assistência Social", "Trabalhador da Assistência Social"],
        ["População Privada de Liberdade", "População Privada de Liberdade"],
    ]
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    CPF = forms.CharField()
    first_name = forms.CharField(label='Nome Completo')
    email = forms.EmailField()
    telefone = forms.CharField()
    endereco = forms.CharField()
    numero = forms.CharField()
    complemento = forms.CharField()
    bairro = forms.CharField()
    CEP = forms.CharField()
    nascimento = forms.DateField(label='Data de Nascimento', localize=True, required=True,
                                 widget=forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'}))
    sexo = forms.ChoiceField(choices=SEXO_CHOICES)
    grupo = forms.ChoiceField(choices=GRUPO_CHOICES)

    class Meta:
        model = Cadastro
        fields = '__all__'

    def __str__(self):
        return self.first_name

# Formulario Agenda de Serviços
class EventForm(forms.ModelForm):
    """Formulário utilizado para a inserção de novos eventos."""

    class Meta:
        model = Event
        fields = ["date", "event", "priority"]

    def __str__(self):
        return self.event


class CommentForm(forms.ModelForm):
    """Formulário usado para a inserção de comentários em um serviço."""

    class Meta:
        model = Comment
        fields = ["text", "author", "email", "event"]

app1/views.py
from datetime import datetime, timedelta

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, InvalidPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.timezone import localdate
from django.views.defaults import bad_request, server_error
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView
from rest_framework import filters, viewsets
from rest_framework.permissions import IsAuthenticated


from app1.forms import EventForm, CommentForm, FormCadastro
from app1.models import Event, Comment, Cadastro
from .serializers import CommentSerializer, EventSerializer
from .services import split_str_date

ITEMS_PER_PAGE = 5
FIRST_PAGE = 1


# PÁGINA PRINCIPAL INDEX
# ----------------------------------------------
def indexx(request):
    return render(request, 'app3/index.html')

# ----------------------------------------------
def noticia(request):
    return render(request, 'app3/noticia.html')

def manutencao(request):
    return render(request, 'app3/manutencao.html')

def cadastro(request):
    if request.method == 'POST':
        form = FormCadastro(request.POST)
        if form.is_valid():
            usuario = User()
            usuario.first_name = form.cleaned_data['first_name']
            usuario.email = form.cleaned_data['email']
            usuario.username = form.cleaned_data['username']
            usuario.password = form.cleaned_data['password']

            usuario.save()
            usuario.set_password(usuario.password)
            usuario.save()

            cad = Cadastro()
            cad.CPF = form.cleaned_data['CPF']
            cad.nascimento = form.cleaned_data['nascimento']
            cad.telefone = form.cleaned_data['telefone']
            cad.endereco = form.cleaned_data['endereco']
            cad.complemento = form.cleaned_data['complemento']
            cad.numero = form.cleaned_data['numero']
            cad.bairro = form.cleaned_data['bairro']
            cad.CEP = form.cleaned_data['CEP']
            cad.grupo = form.cleaned_data['grupo']
            cad.sexo = form.cleaned_data['sexo']

            cad.usuario = usuario
            cad.save()
            return HttpResponseRedirect(reverse('app1:lista_cadastro'))
    else:
        form = FormCadastro()

    return render(request, 'app3/cadastrar.html', {'form': form})

# PÁGINA PRINCIPAL FUNCIONARIO
# ----------------------------------------------

class IndexCadastroTemplateView(TemplateView):
    template_name = "app3/principal.html"

# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroListView(ListView):
    template_name = "app3/lista.html"
    model = Cadastro
    context_object_name = "cadastrado"


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroUpdateView(UpdateView):
    template_name = "app3/confirmar.html"
    model = Cadastro
    fields = '__all__'
    context_object_name = 'cadastro'
    success_url = reverse_lazy("app1:lista_cadastro")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroDeleteView(DeleteView):
    template_name = "app3/index.html"
    model = Cadastro
    context_object_name = 'cadastro'
    success_url = reverse_lazy("app1:lista_cadastro")

# PÁGINA PRINCIPAL LOGIN
# ----------------------------------------------
def loginn(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')
        senha = request.POST.get('senha')
        user = authenticate(username=usuario, password=senha)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app1:indexx'))
            else:
                return HttpResponse("Sua Conta Não Esta Ativa.")
        else:
            print("Alguém Tentou Fazer Login e Falhou")
            print("Foi Usado userName: {} e senha: {}".format(usuario, senha))
            return HttpResponse("O Login ou Senha Está Incorreto.")

    else:
        return render(request, 'app3/login.html', {})

# PÁGINA PRINCIPAL LOGOUT
# ----------------------------------------------
@login_required
def logoutt(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

class EventViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Event.objects.all()
    serializer_class = EventSerializer

    permission_classes = (IsAuthenticated,)


class CommentViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ("event__id",)

    permission_classes = (IsAuthenticated,)

# PÁGINA PRINCIPAL AGENDA
# ----------------------------------------------
@login_required
def agenda(request):
    """
    Exibe a página principal da aplicaão.
    """
    context = {
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/agenda.html", context)


@login_required
def all(request):
    """
    Exibe todas os eventos consolidados em uma única página, recebe o
    número da página a ser visualizada via GET.
    """

    page = request.GET.get("page", FIRST_PAGE)
    paginator = Paginator(Event.objects.all(), ITEMS_PER_PAGE)
    total = paginator.count

    try:
        events = paginator.page(page)
    except InvalidPage:
        events = paginator.page(FIRST_PAGE)

    context = {
        "events": events,
        "total": total,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/events.html", context)


@login_required
def day(request, year: int, month: int, day: int):
    """
    Visualização dos eventos de um determinado dia, recebe a data em
    formato ano/mês/dia como parâmtro.
    """


    day = datetime(year, month, day)
    filted_events = Event.objects.filter(
        date="{:%Y-%m-%d}".format(day)
    ).order_by("-priority", "event")

    context = {
        "today": localdate(),
        "day": day,
        "events": filted_events,
        "next": day + timedelta(days=1),
        "previous": day - timedelta(days=1),
        "priorities": Event.priorities_list,
    }

    return render(request, "app3/agenda/day.html", context)


@login_required
def delete(request, id: int):
    """
    Apaga um evento específico, se o evento não existir resultará em
    erro 404, se algo errado ocorrer retornará a página de erro.
    """
    event = get_object_or_404(Event, id=id)
    (year, month, day) = split_str_date("{:%Y-%m-%d}".format(event.date))

    if event.delete():
        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return server_error(request, "ops_500.html")


@login_required
def edit(request):
    """
    Edita o conteúdo de um evento, recebendo os dados enviados pelo
    formulário, validando e populando em um evento já existente.
    """
    form = EventForm(request.POST)

    if form.is_valid():
        event = get_object_or_404(Event, id=request.POST["id"])
        event.date = form.cleaned_data["date"]
        event.event = form.cleaned_data["event"]
        event.priority = form.cleaned_data["priority"]
        event.save()
        (year, month, day) = split_str_date("{:%Y-%m-%d}".format(event.date))
        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return bad_request(request, None, "ops_400.html")


@login_required
def new(request):
    """
    Recebe os dados de um novo evento via POST, faz a validação dos dados
    e aí insere na base de dados.
    """
    form = EventForm(request.POST)

    if form.is_valid():
        form.save(commit=True)
        # e uso a data enviada pelo formulário para o redirecionamento.
        year, month, day = split_str_date(request.POST["date"])

        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return bad_request(request, None, "ops_400.html")


def show(request, id: int):
    """
    Visualização de um determinado evento e de seus comentários, recebe
    o 'id' do evento. Caso seja acessado via POST insere um novo comentário.
    """
    event = get_object_or_404(Event, id=id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("app1:agenda-events-show", id=id)

    context = {
        "event": event,
        "comments": Comment.objects.filter(event=id).order_by("-commented"),
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/show.html", context)

app1/templates/app3/agendamento.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}
{% load static %}
{% block conteudo %}

<html lang="pt-br">
    <head>


        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
        <title>Laboratório de Informática - Fevereiro/2022</title>

        <link rel='shortcut icon' type='image/x-icon' href='/static/agenda/img/favico.ico' />




<link href="/static/material/fonts/material-design-icons/material-icons.css"  rel="stylesheet">

<link href="/static/material/css/materialize.frontend.min.css" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="/static/agenda/css/base.css" />


    <link rel='stylesheet' href="/static/agenda/css/mes.css" type='text/css' />
    <link rel="stylesheet" type="text/css" href="/static/agenda/css/topbar.css" />
    <link rel='stylesheet' href="/static/agenda/fullcalendar/fullcalendar.css" />



    <script src="/static/material/js/jquery.js"></script>
    <script src="/static/material/js/materialize.js"></script>
    <script src="/static/agenda/fullcalendar/lib/moment.min.js"></script>
    <script src="/static/agenda/fullcalendar/fullcalendar.js"></script>




        <link rel='shortcut icon' type='image/x-icon' href='/static/agenda/img/favico.ico' />


    </head>
    <body class="with-sidebar">

        <header>

            <ul id="slide-out" class="side-nav fixed" data-turbolinks-permanent>

                <li>
                    <div class="userView">
                        <img class="background" src="/static/material/imgs/sidenav.svg">


<a href="#"><i class="circle material-icons medium">location_on</i></a>


                        <a href="#"><span class="white-text name"></span></a>
                        <a href="#"><span class="white-text email"></span></a>
                    </div>
                </li>



    <li><a href="/">Site Principal<i class="material-icons">home</i></a></li>
    <li><a href="/faq/">FAQ/Instruções<i class="material-icons">help</i></a></li>
    <li><a href="/estatisticas/">Estatisticas<i class="material-icons">assessment</i></a></li>
    <li><a href="/sobre">Sobre<i class="material-icons">info</i></a></li>

    <li><a href="/admin/login/">Login<i class="material-icons">exit_to_app</i></a></li>
    <!--<li><a href="/accounts/register/">Registrar<i class="material-icons">exit_to_app</i></a></li> -->






            </ul>

        </header>
        <main>


            <nav class="topbar">
                <div class="nav-wrapper">
                    <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
                    <div class="brand-logo">

    <span class="name">Laboratório de Informática</span>

                    </div>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">


                        <li><a href="/accounts/login/" data-turbolinks="false"><i class="material-icons right">lock_open</i>Acessar</a></li>


                    </ul>
                </div>
            </nav>


            <nav class="breadcrumbs">
                <div class="nav-wrapper">

                </div>
            </nav>


            <div class="content">

<div class="row">
    <div id="calendar"> </div>
</div>
<script type="text/javascript">

jQuery(document).ready(function() {
   jQuery('#calendar').fullCalendar({
        monthNames:["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
        dayNamesShort:["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
        firstDay: 1,

        events: [

        ],
        eventAfterAllRender: function() {
            $(".fc-day-top").each(function(index,value) {
                if(value.className.indexOf("fc-other-month") === -1) {
                    var a = $(value).children().text();
                    var x = ("0"+a).slice(-2);
                    $(value).append("<a href='#'><i class=material-icons>add_circle</i></a>");
                    $(value).css('text-align', 'center');

                }
           });
        },
        eventClick: function(event, jsEvent, view) {
            $('#description').html(event.description);
            $('#modalTitle').html(event.title);
            $('#fullCalModal').modal('open');
        }

    });
    setMonth();
    var m = jQuery(".fc-left").text();
    jQuery(".fc-header-toolbar").html("<div class='row'><a class='btn right col s3' href='/mes/f/3/2022/2/next/'><i class='material-icons medium arrow_right'>arrow_forward</i><span class='text'>próximo</span></a><a class='btn left col s3' href='/mes/f/3/2022/2/prev/'><i class='material-icons medium arrow_left'>arrow_back</i><span class='text'>anterior</span></a><div class='col s6'><h2>" + m + "</h2><a href='/locavel/f/3/' class='flow-text'>Detalhes do locável</a></div></div>");

    // Add listener to buttons
    $('.fc-day-top i').on('click', function(event) {
        event.preventDefault();
        var data = $(this).parent().parent().children('.fc-day-number').text();
        if (data.length == 1) data = '0'+data;
        var month = '2';
        if (month.length == 1) month = '0'+month;
        data += month+'2022';
        sendRequest(data);
    });
    $(".button-collapse").sideNav();
    $('#fullCalModal').modal();
    $('#close-modal').on('click', function() {
        $('#fullCalModal').modal('close');
    });

    $('#calendar').fullCalendar('option', 'height', $('main').height() - $('.topbar').height());
});

function setMonth() {
    if(2>9) {
        var date = $.fullCalendar.moment("2022-2-01");
            $("#calendar").fullCalendar('gotoDate', date);
    } else {
        var date = $.fullCalendar.moment("2022-02-01");
            $("#calendar").fullCalendar('gotoDate', date);
        }
}

// Give required data to session and redirect
function sendRequest(data) {
    $.ajax({
        type: 'GET',
        url: '/reservar/',
        data: {
            data: data,
            id: 3
        },
        dataType: 'json',
        success: function(data) {
            if (data.success) {
                if ('f' === 'f') {
                    location.href = '/admin/agenda/reservaespacofisico/add/';
                } else if ('f' === 'e') {
                    location.href = '/admin/agenda/reservaequipamento/add/';
                } else if ('f' === 's') {
                    location.href = '/admin/agenda/reservaservico/add/'
                }
            }
        }
    });
}
</script>

<!-- Modals structure -->
<div id="fullCalModal" class="modal fade">
        <div class="modal-content">
            <h5 id='modalTitle'></h5>
            <p id='description'></p>
        </div>
        <div class="modal-footer">
            <button id='close-modal' class="light-blue darken-4 btn waves-effect waves-light"><i class='material-icons'>close</i>
            </button>
        </div>
</div>

            </div>


        </main>
        <footer>

        </footer>




    </body>
</html>

{% endblock %}

app1/templates/app3/index.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}
{% load static %}

{% block conteudo %}

     <style>
        .imagem {
            position: absolute;
            z-index: -1;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background-color: #d5d6da;
            opacity: .75;
            width: 100%;
            height: 100%;
        }
        .conteudo {
            font-family: "Century Gothic";
            font-size: 1em;
            line-height: 8vh;
        }
    </style>
  <body class="d-flex flex-column h-100">
    <main role="main" class="flex-shrink-0" style="padding: 60px 15px 0;">
        <div class="imagem"></div>
          <link rel="stylesheet" href="{% static "app2/css/index.css" %}">
        <div class="conteudo"></div>
             <div class="row align-items-center">
                <div class="col align-self-center">
                   <div class="mt-5 text-center">
                         <h1 style="color: black;">Olá.</h1>
                      {% if user.is_authenticated %}
                          <h2 style="color: black;">Seja Bem Vindo!</h2>
                      {% else %}
                          <h2 style="color: black;">Seja Bem Vindo, Desconhecido!</h2>
                      {% endif %}
                   </div>
                </div>
             </div>
          </div>
        </div>
    </main>
  </body>
{% endblock %}

app1/templates/app3/login.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}
{% load static %}
{% block conteudo %}



        <head>
            <meta charset="UTF-8">
            <title>Vacinação Covid-19 | Login</title>
            <link rel="stylesheet" href={% static "app2/css/stylelogin.css" %}>
            <!-- Favicon -->
           <link rel="shortcut icon" href="{% static 'app2/imgs/logo.png' %}" type="image/png">
        </head>
    <body>

        <div class="logo">
            <a href="{% url 'app1:indexx' %}"><img src="{% static "app2/imgs/logo.png" %}" class="logo" alt="Minha Imagem"></a>
        </div>
        <div class="login-box">

            <form method="post" action="{% url 'app1:login' %}">
                {% csrf_token %}
                <h1>Login</h1>
                <div class="textbox">
                    <i class="fas fa-user"></i>
                    <input type="text" name="usuario" placeholder="Usuário">
                </div>
                <div class="textbox">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="senha" placeholder="Senha">
                </div>

                <input type="submit" class="btn" value="Entrar">
            </form>


        </div>



    </body>


{% endblock %}

app1/templates/app3/manutencao.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}
{% load static %}

{% block conteudo %}
<head>
    <meta charset="UTF-8">
<style>
        .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-top: 150px;
  width: 30%;
  background-color: #bbbbbb;
}
</style>
         <img class="rounded mx-auto d-block center"  alt="Base Security" src="{% static "app2/imgs/fundo-manu.png" %}" type="image/png">

    <title>Title</title>
</head>
<body>

</body>
{% endblock %}

app1/templates/app3/noticia.html
<!DOCTYPE html>
{% extends "app3/_layouts/base.html" %}
{% load static %}

{% block conteudo %}

  <body>

<iframe src="https://covid.saude.gov.br/" style="border:none;"  width="100%" height="7267" class="responsive-iframe"></iframe>

  </body>
{% endblock %}

app1/templates/app3/principal.html
<!-- Estendemos do template base -->
{% extends "app3/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Funcionário{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5" style="margin-top: 50">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Funcionário</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Funcionário</code>.
          </p>
          <a href="{% url 'app1:cadastrar' %}" class="btn btn-success">Novo Funcionário</a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Funcionários</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Funcionários</code> cadastrados.
          </p>
          <a href="{% url 'app1:lista_cadastro' %}" class="btn btn-primary">Vá para Lista</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}