app1/urls.py
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from django.urls import path, include

from . import views
from .views import CadastroListView, CadastroUpdateView, CadastroDeleteView, IndexCadastroTemplateView

router = routers.DefaultRouter()
router.register(r"events", views.EventViewSet)
router.register(r"comments", views.CommentViewSet)

app_name = 'app1'

urlpatterns = [
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),
    path('noticia', views.noticia, name='noticia'),
    path('manutencao', views.manutencao, name='manutencao'),
    path('api-token-auth/', obtain_auth_token, name="api_token_auth"),
    path('cadastro/', views.cadastro, name="cadastrar"),
    path('cadastrado', CadastroListView.as_view(), name="lista_cadastro"),
    path('cadastro/<pk>', CadastroUpdateView.as_view(), name="atualiza_cadastro"),
    path('cadastro/excluir/<pk>', CadastroDeleteView.as_view(), name="deleta_cadastro"),
    path('principalcadastro/', IndexCadastroTemplateView.as_view(), name="principal_cadastro"),
    path("api/v1/", include(router.urls)),
    path("agenda", views.agenda, name="agenda-events"),
    path("all", views.all, name="agenda-events-all"),
    path("<int:id>", views.show, name="agenda-events-show"),
    path("<int:year>/<int:month>/<int:day>", views.day, name="agenda-events-day"),
    path("new", views.new, name="agenda-events-new"),
    path("delete/<int:id>", views.delete, name="agenda-events-delete"),
    path("edit", views.edit, name="agenda-events-edit"),

]

covid/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path
from app1 import views


urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name="admin"),
]

app1/forms.py
from django import forms
from django.contrib.auth.models import User
from django_cpf_cnpj.fields import CPFField

from app1.models import Cadastro, Comment, Event


# Fomulario Cadastro
class FormCadastro(forms.Form):
    SEXO_CHOICES = [
        ["Feminino", "Feminino"],
        ["Masculino", "Masculino"]
    ]
    GRUPO_CHOICES = [
        ["Selecione uma Opção", "Selecione uma Opção"],
        ["Profissional de saúde", "Profissional de saúde"],
        ["Trabalhador em saúde sem conselho de classe", "Trabalhador em saúde sem conselho de classe"],
        ["Doula", "Doula"],
        ["Cuidador", "Cuidador"],
        ["Acamado com 60 anos ou mais", "Acamado com 60 anos ou mais"],
        ["Pessoa com 80 anos ou mais", "Pessoa com 80 anos ou mais"],
        ["Pessoa entre 75 e 79 anos", "Pessoa entre 75 e 79 anos"],
        ["Pessoa entre 70 e 74 anos", "Pessoa entre 70 e 74 anos"],
        ["Pessoa entre 65 e 69 anos", "Pessoa entre 65 e 69 anos"],
        ["Pessoa entre 60 e 64 anos", "Pessoa entre 60 e 64 anos"],
        ["População Geral de 45 a 59 anos", "População Geral de 45 a 59 anos"],
        ["Policial Militar", "Policial Militar"],
        ["Policial Civil", "Policial Civil"],
        ["Policial Federal", "Policial Federal"],
        ["Agente da Receita Federal", "Agente da Receita Federal"],
        ["Policial Rodoviário", "Policial Rodoviário"],
        ["Agente Penitenciário / Policial Penal", "Agente Penitenciário / Policial Penal"],
        ["Trabalhadores de Unidades Socioeducativas", "Trabalhadores de Unidades Socioeducativas"],
        ["Trabalhador do Sistema Prisional", "Trabalhador do Sistema Prisional"],
        ["Bombeiro Civil", "Bombeiro Civil"],
        ["Bombeiro Militar", "Bombeiro Militar"],
        ["Guarda Municipal", "Guarda Municipal"],
        ["Membro do Exército", "Membro do Exército"],
        ["Membro da Marinha", "Membro da Marinha"],
        ["Membro da Aeronáutica", "Membro da Aeronáutica"],
        ["Trabalhador de Transporte Aéreo", "Trabalhador de Transporte Aéreo"],
        ["Professor", "Professor"],
        ["Trabalhador da Educação", "Trabalhador da Educação"],
        ["Assistente Social", "Assistente Social"],
        ["Trabalhador da Assistência Social", "Trabalhador da Assistência Social"],
        ["População Privada de Liberdade", "População Privada de Liberdade"],
    ]
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    CPF = forms.CharField()
    first_name = forms.CharField(label='Nome Completo')
    email = forms.EmailField()
    telefone = forms.CharField()
    endereco = forms.CharField()
    numero = forms.CharField()
    complemento = forms.CharField()
    bairro = forms.CharField()
    CEP = forms.CharField()
    nascimento = forms.DateField(label='Data de Nascimento', localize=True, required=True,
                                 widget=forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'}))
    sexo = forms.ChoiceField(choices=SEXO_CHOICES)
    grupo = forms.ChoiceField(choices=GRUPO_CHOICES)

    class Meta:
        model = Cadastro
        fields = '__all__'

    def __str__(self):
        return self.first_name

# Formulario Agenda de Serviços
class EventForm(forms.ModelForm):
    """Formulário utilizado para a inserção de novos eventos."""

    class Meta:
        model = Event
        fields = ["date", "event", "priority"]

    def __str__(self):
        return self.event


class CommentForm(forms.ModelForm):
    """Formulário usado para a inserção de comentários em um serviço."""

    class Meta:
        model = Comment
        fields = ["text", "author", "email", "event"]

app1/views.py
from datetime import datetime, timedelta

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, InvalidPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.timezone import localdate
from django.views.defaults import bad_request, server_error
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView
from rest_framework import filters, viewsets
from rest_framework.permissions import IsAuthenticated


from app1.forms import EventForm, CommentForm, FormCadastro
from app1.models import Event, Comment, Cadastro
from .serializers import CommentSerializer, EventSerializer
from .services import split_str_date

ITEMS_PER_PAGE = 5
FIRST_PAGE = 1


# PÁGINA PRINCIPAL INDEX
# ----------------------------------------------
def indexx(request):
    return render(request, 'app3/index.html')

# ----------------------------------------------
def noticia(request):
    return render(request, 'app3/noticia.html')

def manutencao(request):
    return render(request, 'app3/manutencao.html')

def cadastro(request):
    if request.method == 'POST':
        form = FormCadastro(request.POST)
        if form.is_valid():
            usuario = User()
            usuario.first_name = form.cleaned_data['first_name']
            usuario.email = form.cleaned_data['email']
            usuario.username = form.cleaned_data['username']
            usuario.password = form.cleaned_data['password']

            usuario.save()
            usuario.set_password(usuario.password)
            usuario.save()

            cad = Cadastro()
            cad.CPF = form.cleaned_data['CPF']
            cad.nascimento = form.cleaned_data['nascimento']
            cad.telefone = form.cleaned_data['telefone']
            cad.endereco = form.cleaned_data['endereco']
            cad.complemento = form.cleaned_data['complemento']
            cad.numero = form.cleaned_data['numero']
            cad.bairro = form.cleaned_data['bairro']
            cad.CEP = form.cleaned_data['CEP']
            cad.grupo = form.cleaned_data['grupo']
            cad.sexo = form.cleaned_data['sexo']

            cad.usuario = usuario
            cad.save()
            return HttpResponseRedirect(reverse('app1:lista_cadastro'))
    else:
        form = FormCadastro()

    return render(request, 'app3/cadastrar.html', {'form': form})

# PÁGINA PRINCIPAL FUNCIONARIO
# ----------------------------------------------

class IndexCadastroTemplateView(TemplateView):
    template_name = "app3/principal.html"

# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroListView(ListView):
    template_name = "app3/lista.html"
    model = Cadastro
    context_object_name = "cadastrado"


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroUpdateView(UpdateView):
    template_name = "app3/confirmar.html"
    model = Cadastro
    fields = '__all__'
    context_object_name = 'cadastro'
    success_url = reverse_lazy("app1:lista_cadastro")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class CadastroDeleteView(DeleteView):
    template_name = "app3/index.html"
    model = Cadastro
    context_object_name = 'cadastro'
    success_url = reverse_lazy("app1:lista_cadastro")

# PÁGINA PRINCIPAL LOGIN
# ----------------------------------------------
def loginn(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuario')
        senha = request.POST.get('senha')
        user = authenticate(username=usuario, password=senha)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app1:indexx'))
            else:
                return HttpResponse("Sua Conta Não Esta Ativa.")
        else:
            print("Alguém Tentou Fazer Login e Falhou")
            print("Foi Usado userName: {} e senha: {}".format(usuario, senha))
            return HttpResponse("O Login ou Senha Está Incorreto.")

    else:
        return render(request, 'app3/login.html', {})

# PÁGINA PRINCIPAL LOGOUT
# ----------------------------------------------
@login_required
def logoutt(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

class EventViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Event.objects.all()
    serializer_class = EventSerializer

    permission_classes = (IsAuthenticated,)


class CommentViewSet(viewsets.ModelViewSet):
    """
    Disponibiliza os eventos da agenda como uma API REST.
    """

    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ("event__id",)

    permission_classes = (IsAuthenticated,)

# PÁGINA PRINCIPAL AGENDA
# ----------------------------------------------
@login_required
def agenda(request):
    """
    Exibe a página principal da aplicaão.
    """
    context = {
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/agenda.html", context)


@login_required
def all(request):
    """
    Exibe todas os eventos consolidados em uma única página, recebe o
    número da página a ser visualizada via GET.
    """

    page = request.GET.get("page", FIRST_PAGE)
    paginator = Paginator(Event.objects.all(), ITEMS_PER_PAGE)
    total = paginator.count

    try:
        events = paginator.page(page)
    except InvalidPage:
        events = paginator.page(FIRST_PAGE)

    context = {
        "events": events,
        "total": total,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/events.html", context)


@login_required
def day(request, year: int, month: int, day: int):
    """
    Visualização dos eventos de um determinado dia, recebe a data em
    formato ano/mês/dia como parâmtro.
    """


    day = datetime(year, month, day)
    filted_events = Event.objects.filter(
        date="{:%Y-%m-%d}".format(day)
    ).order_by("-priority", "event")

    context = {
        "today": localdate(),
        "day": day,
        "events": filted_events,
        "next": day + timedelta(days=1),
        "previous": day - timedelta(days=1),
        "priorities": Event.priorities_list,
    }

    return render(request, "app3/agenda/day.html", context)


@login_required
def delete(request, id: int):
    """
    Apaga um evento específico, se o evento não existir resultará em
    erro 404, se algo errado ocorrer retornará a página de erro.
    """
    event = get_object_or_404(Event, id=id)
    (year, month, day) = split_str_date("{:%Y-%m-%d}".format(event.date))

    if event.delete():
        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return server_error(request, "ops_500.html")


@login_required
def edit(request):
    """
    Edita o conteúdo de um evento, recebendo os dados enviados pelo
    formulário, validando e populando em um evento já existente.
    """
    form = EventForm(request.POST)

    if form.is_valid():
        event = get_object_or_404(Event, id=request.POST["id"])
        event.date = form.cleaned_data["date"]
        event.event = form.cleaned_data["event"]
        event.priority = form.cleaned_data["priority"]
        event.save()
        (year, month, day) = split_str_date("{:%Y-%m-%d}".format(event.date))
        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return bad_request(request, None, "ops_400.html")


@login_required
def new(request):
    """
    Recebe os dados de um novo evento via POST, faz a validação dos dados
    e aí insere na base de dados.
    """
    form = EventForm(request.POST)

    if form.is_valid():
        form.save(commit=True)
        # e uso a data enviada pelo formulário para o redirecionamento.
        year, month, day = split_str_date(request.POST["date"])

        return redirect("app1:agenda-events-day", year=year, month=month, day=day)
    else:
        return bad_request(request, None, "ops_400.html")


def show(request, id: int):
    """
    Visualização de um determinado evento e de seus comentários, recebe
    o 'id' do evento. Caso seja acessado via POST insere um novo comentário.
    """
    event = get_object_or_404(Event, id=id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("app1:agenda-events-show", id=id)

    context = {
        "event": event,
        "comments": Comment.objects.filter(event=id).order_by("-commented"),
        "hide_new_button": True,
        "priorities": Event.priorities_list,
        "today": localdate(),
    }

    return render(request, "app3/agenda/show.html", context)

app1/templates/app3/agenda/modals/edit.html
    <!-- Modal Edição da Agenda-->
<style>
    .modal-open .modal {
    overflow-x: hidden;
    overflow-y: auto;
}
    .modal {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1050;
    display: none;
    width: 100%;
    height: 100%;
    overflow: hidden;
    outline: 0;
}
    .fade {
    transition: opacity .15s linear;
}
</style>
    <div class="modal fade" id="editEvent" tabindex="-1" role="dialog" aria-labelledby="editEventLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <form action="{% url 'app1:agenda-events-edit' %}" enctype="multipart/form-data" method="post">
            <div class="modal-header">
              <h5 class="modal-title" id="editEventLabel">Editar</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              {% csrf_token %}
              <input type="hidden" id="editInputId" name="id" value="">
              <div class="form-group">
                <label for="editInputDate">Data</label>
                <input type="date" class="form-control" id="editInputDate" name="date" placeholder="Data" value="{{ day|date:'Y-m-d' }}" required>
              </div>
              <div class="form-group">
                <label for="editInputEvent">CPF</label>
                <input type="text" class="form-control" id="editInputEvent" name="event" placeholder="000.000.000-00" required>
              </div>
              <div class="form-group">
                <label for="editInputPriority">Prioridade</label>
                <select class="form-control" id="editInputPriority" name="priority">
                {% for value, priority in priorities %}
                  <option value="{{ value }}">{{ priority }}</option>
                {% endfor %}
                </select>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-primary">Editar</button>
            </div>
            </div>
          </form>
        </div>
      </div>
    </div>

app1/templates/app3/agenda/modals/new.html
    <!-- Modal Criação de Serviço Agenda -->
{% load static %}
{% load widget_tweaks %}

    {% if hide_new_button != True %}
    <div class="container text-center">

      <a href="{% url 'app1:agenda-events-day' today.year today.month today.day %}" class="btn btn-primary mb-auto">Agenda de Hoje</a>
      <a href="{% url 'app1:agenda-events-all' %}" class="btn btn-warning mb-auto">Todos Agendamentos</a>
      <button type="submit" class="btn btn-success mt-3 mb-3" data-toggle="modal" data-target="#addEvent">Novo Agendamento</button>
    <hr/>
    <hr/>
    </div>
      <hr/>
     <hr/>
    {% endif %}
 <style>
        .img-fluid {
            max-width: 100%;
            height: auto;
        }
        .modal-open .modal {
    overflow-x: hidden;
    overflow-y: auto;
}
        .modal {
    position: fixed;
    top: 100px;
    left: 0;
    z-index: 1050;
    display: none;
    width: 100%;
    height: 100%;
    overflow: hidden;
    outline: 0;
}

    </style>

    <div class="modal fade" id="addEvent" tabindex="-1" role="dialog" aria-labelledby="addEventLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <form action="{% url 'app1:agenda-events-new' %}" enctype="multipart/form-data" method="post">
            <div class="modal-header">
              <h5 class="modal-title" style="font-size: 20px" id="addEventLabel">Agendamento</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              {% csrf_token %}
              <div class="form-group">
                <label for="addInputDate">Data</label>
                <input type="date" class="form-control" id="addInputDate" name="date" placeholder="Data" value="{{ today|date:'Y-m-d' }}" required>
              </div>
              <div class="form-group">
                <label for="addInputEvent">CPF</label>
                <input type="text" class="form-control" id="addInputEvent" name="event" placeholder="000.000.00-00" required>
              </div>
              <div class="form-group">
                <label for="editInputPriority">Prioridade</label>
                <select class="form-control" id="editInputPriority" name="priority">
                {% for value, priority in priorities %}
                  <option value="{{ value }}">{{ priority }}</option>
                {% endfor %}
                </select>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-primary">Inserir</button>
            </div>
            </div>
          </form>
        </div>
      </div>
    </div>